---
- name: Cisco show running-config
  hosts: nexus
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: nxos
    ansible_user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') | default('admin', true) }}"
    ansible_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') | default('password', true) }}"

  tasks:
   - name: Run "show running-config"
     cisco.nxos.nxos_command:
       commands:
         - show running-config
     register: output



# - name: Configure VLAN on Cisco Switches
#   hosts: nexus
#   gather_facts: no
#   tasks:
#     - name: Configure VLAN 100 on switch
#       ios_config:
#         lines:
#           - vlan 120
#           - name Marketing
#         save_when: modified