
hostname: NXOS9k5

layer3_physical_interfaces: &l3
  - interface: Ethernet1/1
    description: To L1 Eth1/11
    ip_address: 10.1.1.0
    mask: 31
    mtu: 9216
  - interface: Ethernet1/2
    description: To L2 Eth1/11
    ip_address: 10.1.1.2
    mask: 31
    mtu: 9216

loopback_interfaces: &lo
  - interface: loopback0
    description: Routing Loopback
    ip_address: 10.0.0.1
    mask: 32
  - interface: loopback250
    description: PIM Anycast RP Loopback
    ip_address: 10.250.250.1
    mask: 32

all_layer3_interfaces:
  - *l3
  - *lo

