hostname: NXOS9k4

layer3_physical_interfaces: &l3
  - interface: Ethernet1/1
    description: Link to NXOS9k3 Eth1/2
    ip_address: 192.168.1.7
    mask: 31
    mtu: 9216

loopback_interfaces: &lo
  - interface: loopback0
    description: Routing Loopback
    ip_address: 4.4.4.4
    mask: 32

all_layer3_interfaces:
- *l3
- *lo
