
hostname: NXOS9k1 

host_enabled_features: 
 - l2vpn 
 - l3vpn
 - bfd

layer3_physical_interfaces: &l3
  - interface: Ethernet1/1
    description: Link to NXOS9k2 Eth1/2
    ip_address: 192.168.1.3
    mask: 31
    mtu: 9216
  - interface: Ethernet1/2
    description: Link to NXOS9k3 Eth1/1
    ip_address: 192.168.1.4
    mask: 31
    mtu: 9216

loopback_interfaces: &lo
  - interface: loopback0
    description: Routing Loopback
    ip_address: 1.1.1.1
    mask: 32
  # - interface: loopback250
  #   description: PIM Anycast RP Loopback
  #   ip_address: 10.250.250.1
  #   mask: 32

all_layer3_interfaces:
  - *l3
  - *lo
